Update covid-flow.js
pjayathissa/cozie-covid pull request #15
Opened 2020-04-11 07:32 UTC by Ananya-Joshi

Changed icon names and icon colors.

2020-04-11 13:41 UTC, LionelKarlen reviewed
Everything looks fine codewise and the colors look great but the icons are stretched and are inconsistently aliased. Could someone look into that?

2020-04-12 06:13 UTC, pjayathissa commented
@Ananya-Joshi I just realised the issue. The icons have to be square. Otherwise they get wierdly stretched. Do you mind redoing the icons in a non-stretched state? Sorry, I should have checked this before merging your other pull request

2020-04-12 06:21 UTC, pjayathissa requested changes
You will have to do the following. 

- [x] Merge the master branch into `Ananya-Joshi-patch-2`. You can do this with the command `git merge master` in your terminal from your root directory.
- [x] Change the icons so that they are square, and ideally around 1kb if possible
- [x] Can you rename the icons so that they are grouped. This makes it a lot easier in the future. For example all the icons in the cough difference screen should be labelled `cough_low.png`, `cough_med.png`, `cough_high.png`. Same for `lethargy`. This makes it easier to find the icons. The `breath` icons for example are labelled well.
- [x] Also, `neutral.png` is spelt wrong
- [x] `fever_low.png` is missing

2020-04-13 04:28 UTC, pjayathissa approved these changes

2020-04-13 04:32 UTC, merged